### ISSUE TITLE
Finding CPB - device unavailable

### ISSUE THREAD

**Issue by CollinCunningham** [FoamyGuy/Android_Bluefruit_Playground#1]
I'm having issue reconnecting to Circuit Playground Bluefruit after using the app w it.

Hardware: Nexus 7
Android version: 6.0.1

Steps to reproduce:
1. connect to Circuit Playground Bluefruit and use various modules
2. disconnect CPB from app
3. scan again for CPB
4. CPB does not appear in list

Let me know if there's any other information I can provide.

**Comment by FoamyGuy** [comment]
Thank you, I will look into this issue.
For step 2, disconnect CPB from app, did you use the disconnect button at the top left of the modules list activity? Or click the item in the notification entry?

**Comment by CollinCunningham** [comment]
Testing this again. Yes - I must have turned the service off from the notification tray. Using the regular app’s Disconnect button appears to work fine currently. Turning off via the notification causes issues.

**Comment by FoamyGuy** [comment]
Okay, I've given some thought to the notification as well. I think I am going to remove the ability to click to exit the service. I think it's confusing that there are seemingly two ways to exit/disconnect. 

Instead I'm thinking the app will always disconnect and exit the service whenever the user navigates away via home key or recent apps or anything else coming into the foreground. 

If they use the physical back key or the on screen back buttons in the top left then they'll eventually end up at the "Finding CPB" activity. To provide some continuity with the other pages I'll add an "exit" button in the top left.

With those changes the users are naturally funneled toward only one way to exit/disconnect and anytime the app goes to background for any other reason the service will stop itself anyway and there is no need for the notification to do it.

**Comment by FoamyGuy** [comment]
I've made the changes outlined above and there is a new v07 apk in the repo that includes these as well as a few other minor bugfixes that I noticed while working on the changes. 

I believe this version should eliminate the possibility of broken states like the one you observed. When you have a moment give it a try and let me know if you see this issue pop up any more.

**Comment by CollinCunningham** [comment]
Thanks @FoamyGuy - looks good 🎉 
There's two other smaller things I noticed which I'll create issues for.
