### ISSUE TITLE
About view

### ISSUE THREAD

**Issue by CollinCunningham** [FoamyGuy/Android_Bluefruit_Playground#2]
Could you add a button on the Finding CPB screen that opens an "About" view with the app name and the following info below it?

> Bluefruit Playground is designed for use with [Circuit Playground Bluefruit](https://www.adafruit.com/product/4333).
> 
> Before you can use this app, you'll need to load a specific [uf2 firmware file](https://learn.adafruit.com/bluefruit-playground-app/firmware) on your Circuit Playground Bluefruit. 
> 
> Learn more at the [Adafruit Learning System](https://learn.adafruit.com/bluefruit-playground-app/overview).

Also pls include a developer credit for yourself if you're comfortable doing so. Thanks!

**Comment by FoamyGuy** [comment]
v09 apk file has been added to the repo. This version contains the About page, as well as several other additions.
